import 'vuetify/styles'
import '@mdi/font/css/materialdesignicons.css'
import { createVuetify } from 'vuetify'
import {
  VAlert,
  VApp,
  VAppBar,
  VBtn,
  VBtnToggle,
  VCard,
  VCardActions,
  VCardText,
  VCardTitle,
  VChip,
  VCol,
  VDatePicker,
  VDialog,
  VDivider,
  VForm,
  VIcon,
  VListItem,
  VMain,
  VMenu,
  VRow,
  VSkeletonLoader,
  VSelect,
  VSnackbar,
  VSpacer,
  VTextField,
  VTextarea,
} from 'vuetify/components'
import { Ripple } from 'vuetify/directives'

export const vuetify = createVuetify({
  components: {
    VAlert,
    VApp,
    VAppBar,
    VBtn,
    VBtnToggle,
    VCard,
    VCardActions,
    VCardText,
    VCardTitle,
    VChip,
    VCol,
    VDatePicker,
    VDialog,
    VDivider,
    VForm,
    VIcon,
    VListItem,
    VMain,
    VMenu,
    VRow,
    VSkeletonLoader,
    VSelect,
    VSnackbar,
    VSpacer,
    VTextField,
    VTextarea,
  },
  directives: {
    Ripple,
  },
  theme: {
    defaultTheme: 'light',
    themes: {
      light: {
        dark: false,
        colors: {
          primary: '#2559d6',
          secondary: '#8aa4d6',
          surface: '#ffffff',
          background: '#f3f5ef',
          error: '#cf4b4b',
          warning: '#d08b36',
          success: '#24856f',
          info: '#2559d6',
        },
      },
      dark: {
        dark: true,
        colors: {
          primary: '#7db5ff',
          secondary: '#7d92ba',
          surface: '#182334',
          background: '#101926',
          error: '#ff8b8b',
          warning: '#f0b96a',
          success: '#57c8ab',
          info: '#7db5ff',
        },
      },
    },
  },
  defaults: {
    VBtn: { variant: 'flat', rounded: 'xl', elevation: 0 },
    VCard: { rounded: 'xl', elevation: 0 },
    VTextField: { variant: 'outlined', density: 'comfortable' },
    VSelect: { variant: 'outlined', density: 'comfortable' },
    VTextarea: { variant: 'outlined', density: 'comfortable' },
    VChip: { rounded: 'xl' },
  },
})
